// Model layer for the `public.distress_signals` table.
//
// Maps 1:1 to the Postgres schema:
//   id              uuid            PK
//   drill_event_id  uuid            FK -> drill_events.id
//   student_id      uuid            FK -> profiles.id
//   channel         distress_channel enum ('app' | 'sms' | 'missed_call')
//   latitude        double precision (nullable)
//   longitude       double precision (nullable)
//   building        text            (nullable)
//   floor           text            (nullable)
//   message         text            (nullable)
//   created_at      timestamptz

/// Mirrors the `distress_channel` Postgres enum.
enum DistressChannel {
  app,
  sms,
  missedCall;

  /// Converts the raw Postgres enum value (e.g. 'missed_call') to
  /// its Dart equivalent.
  static DistressChannel fromRaw(String raw) {
    switch (raw) {
      case 'app':
        return DistressChannel.app;
      case 'sms':
        return DistressChannel.sms;
      case 'missed_call':
        return DistressChannel.missedCall;
      default:
        throw ArgumentError('Unknown distress_channel value: $raw');
    }
  }

  /// Converts back to the raw Postgres enum value for inserts/filters.
  String get raw {
    switch (this) {
      case DistressChannel.app:
        return 'app';
      case DistressChannel.sms:
        return 'sms';
      case DistressChannel.missedCall:
        return 'missed_call';
    }
  }

  /// Human readable label for UI display.
  String get label {
    switch (this) {
      case DistressChannel.app:
        return 'In-App SOS';
      case DistressChannel.sms:
        return 'SMS';
      case DistressChannel.missedCall:
        return 'Missed Call';
    }
  }
}

class DistressSignalModel {
  const DistressSignalModel({
    required this.id,
    required this.drillEventId,
    required this.studentId,
    required this.channel,
    required this.createdAt,
    this.latitude,
    this.longitude,
    this.building,
    this.floor,
    this.message,
  });

  final String id;
  final String drillEventId;
  final String studentId;
  final DistressChannel channel;
  final double? latitude;
  final double? longitude;
  final String? building;
  final String? floor;
  final String? message;
  final DateTime createdAt;

  bool get hasLocation => latitude != null && longitude != null;

  factory DistressSignalModel.fromJson(Map<String, dynamic> json) {
    return DistressSignalModel(
      id: json['id'] as String,
      drillEventId: json['drill_event_id'] as String,
      studentId: json['student_id'] as String,
      channel: DistressChannel.fromRaw(json['channel'] as String),
      latitude: (json['latitude'] as num?)?.toDouble(),
      longitude: (json['longitude'] as num?)?.toDouble(),
      building: json['building'] as String?,
      floor: json['floor'] as String?,
      message: json['message'] as String?,
      createdAt: DateTime.parse(json['created_at'] as String).toLocal(),
    );
  }

  /// Payload used for inserts. `id` and `created_at` are generated by
  /// the database, so they're intentionally excluded.
  Map<String, dynamic> toInsertJson() {
    return {
      'drill_event_id': drillEventId,
      'student_id': studentId,
      'channel': channel.raw,
      if (latitude != null) 'latitude': latitude,
      if (longitude != null) 'longitude': longitude,
      if (building != null) 'building': building,
      if (floor != null) 'floor': floor,
      if (message != null) 'message': message,
    };
  }

  DistressSignalModel copyWith({
    String? id,
    String? drillEventId,
    String? studentId,
    DistressChannel? channel,
    double? latitude,
    double? longitude,
    String? building,
    String? floor,
    String? message,
    DateTime? createdAt,
  }) {
    return DistressSignalModel(
      id: id ?? this.id,
      drillEventId: drillEventId ?? this.drillEventId,
      studentId: studentId ?? this.studentId,
      channel: channel ?? this.channel,
      latitude: latitude ?? this.latitude,
      longitude: longitude ?? this.longitude,
      building: building ?? this.building,
      floor: floor ?? this.floor,
      message: message ?? this.message,
      createdAt: createdAt ?? this.createdAt,
    );
  }
}